- README.md
이런거 했어요 
리드미에 test라고 임시로 썼어요 .
- #6
> [✨ Feature] #6 -  깃협업테스트입니다

- src/components/common/CommonFooter.styled.js
- src/layout/DefaultLayout.jsx
- src/pages/chatPage/ChatPage.styled.js
- src/pages/communityPage/CommunityPage.styled.js
- src/pages/mainPage/MainPage.styled.js
- src/pages/myPage/MyPage.styled.js
- src/styles/theme.js
푸터 위쪽으로 올라가는 그림자 추가, 기본페이지 색상 테마에 추가했습니다. 
theme.js에  pageBgColor로  아래와같이 색상 추가하고 DefaultLayout.jsx에 배경색 변경했습니다! 
```
colors: {
//나중에 필요시 추가하기
bg: "#999999", //배경색
mainColor: "#FF6969", //메인컬러
pageBgColor: "#FAFAFC", //페이지 기본 회색 배경색
default: "#000000", // 기본 검정색
white: "#FFFFFF",
},
```
- #21
> 🎨 [Design] #21 - 푸터 그림자추가 페이지 배경색변경

- index.html
- public/test.html
- src/hooks/useKaKaoShare.js
- src/hooks/useShouldHideFooter.js
- src/pages/testPage/TestStartPage.jsx
카카오 공유하기 기능을 임시로 구현했는데 일단 작동은 잘됩니다 추후에 훅이나 이런거 코드좀 리팩토링 하겠습니다.
testStart페이지에만 구현해놨어요 
- #35
> ✨ [Feature] #35 -카카오 공유하기기능 임시적용

- src/router.jsx
라우터파일에서  AgeSignUpPage이 AGe로 설정되어있어서 버셀에서 배포오류난듯요 수정했습니다. 
- #35
> 🐛 [Fix] #35 -라우터 경로오류수정

- src/hooks/useKaKaoShare.js
- src/pages/testPage/TestResultNoPage.jsx
- src/pages/testPage/TestResultOkPage.jsx
- src/pages/testPage/TestStartPage.jsx
헌혈견 테스트 카카오 공유하기 연결완료했습니다. 
테스트의 모든 공유하기버튼을 누르면 자동으로 카카오로 넘어가서 공유할 수 있습니다. 설명과 OG설정도 완료하였음 
useKaKaoShare훅을 만들어서 onClick={() => shareKakao()만 버튼에 넣는다면 공유하기 기능을 사용할 수있음 
빈 객체로 넘기면 기본으로 설정해둔 헌혈견 테스트의 내용이 들어가지만 props로 따로 텍스트,설명,이미지 경로등 공유시 보이는 내용을 수정할수도 있습니다. 
```
const baseUrl =
window.location.hostname === "localhost"
? "http://localhost:5173"
: "https://2024-sharedog-frontend.vercel.app";
```
훅에서 baseurl설정으로 로컬에서도 잘 작동하도록 만들었습니다. 
```
const shareKakao = useCallback(
({
title = "우리집 강아지는 헌혈견이 될 수 있을까?",
description = "테스트를 통해 확인해보세요!",
imageUrl = "https://2024-sharedog-frontend.vercel.app/testThumbnail.png",
pageUrl = `${baseUrl}/testStart`,
} = {}) => {
// 빈 객체를 기본값으로 설정
if (!window.Kakao) {
console.error("Kakao SDK가 로드되지 않았습니다.");
return;
}
window.Kakao.Share.sendDefault({
objectType: …
```
> ✨ [Feature] #35 - 테스트 카카오 공유하기 연결완료

- public/test.html
- vercel.json
테스트 카카오 공유하기가 아이폰 카카오 인앱브라우저에서는 화면 표시가 안돼서 vercel.json을 수정해서 해결해보려고 합니다. 
테스트쪽 이슈를 closed해서 비슷한 카카오쪽인 여기 이슈에 올립니다...
-  #55
> 🐛 [Fix] #55 - 카카오 공유하기 인앱브라우저문제 수정

- src/apis/axiosInstance.js
- src/apis/refreshTokenUtil.js
- src/pages/myPage/AccountManagement.jsx
마이페이지쪽에서 로그아웃구현했고 마이페이지 유저 이메일불러오는 get api도 하나구현했습니다. 
이제 카카오로그인, 로그아웃잘됩니다 
- #55
> ✨ [Feature] #55 - 카카오 로그아웃구현 &&마이페이지 api연결..

- src/pages/myPage/AccountManagement.jsx
- src/pages/myPage/AccountManagement.styled.js
- src/pages/myPage/PetAdd.jsx
- src/pages/myPage/PetAdd.styled.js
- src/pages/myPage/PetInfo.jsx
- src/pages/myPage/PetInfo.styled.js
- src/pages/myPage/Reservation.styled.js
- src/router.jsx
마이페이지 UI(백버튼 등)를 수정하고, 새로운 강아지를 추가하는 PetAdd 페이지 UI를 제작했습니다.
#58
> [Feature] #58 마이페이지 UI 다듬기/강아지 추가 페이지 UI

- src/pages/myPage/PetAdd.jsx
- src/pages/myPage/PetAdd.styled.js
- src/pages/myPage/PetEdit.jsx
- src/pages/myPage/PetInfo.jsx
- src/pages/myPage/PetInfo.styled.js
- src/pages/myPage/Reservation.jsx
- src/pages/myPage/Reservation.styled.js
마이페이지 UI의 미흡한 부분들을 구석구석 다듬었습니다.
#58
> [Design] #58 마이페이지 UI 다듬기

- src/components/post/BloodPostCard.styled.js
- src/pages/communityPage/CommunityPage.styled.js
커뮤니티 게시글이 반응형으로 움직일 때 작게 보이던 UI 문제를 해결했습니다.
#66
> [Design] #66 커뮤니티페이지 글 반응형 수정

- .gitignore
- package-lock.json
- package.json
- vite.config.js
백엔드가 https배포를 했기때문에 웹소켓 테스트를 위해 프론트도 로컬 https로 변경하는 작업을 진행하였습니다. 
vite.config.js에서 env파일을 로드할수있게하는dotenv를 사용했기때문에 npm i한번 하고 작업해주세요 
- #76
> 🔧 [Chore] #76 - 로컬 개발 환경 HTTPS 적용

- src/pages/communityPage/CommunityWrite.jsx
- src/pages/communityPage/CommunityWrite.styled.js
🎨커뮤니티 페이지 UI 구현 완료
Wrapper 바로 아래에서 작업하니까 전체 화면의 사이즈가 안맞아서 Container를 새로 만들어서 margin 값으로해서 width를 100%만 적용해도 정렬이 될 수 있도록 설정했음!
기능은 이제 추가해야함!!ㅜㅜ
- #66
> 🎨 [Design] #66 커뮤니티 페이지 UI 구현 완료

- .gitignore
- src/components/main/LoginRequiredBox.jsx
- src/components/main/LoginRequiredModal.jsx
- src/hooks/useShare.js
- src/pages/mainPage/MainPage.jsx
- src/pages/testPage/TestResultNoPage.jsx
- src/pages/testPage/TestResultOkPage.jsx
- src/pages/testPage/TestStartPage.jsx
- src/styles/theme.js
로그인안하고 둘러보기를 눌렀을때 게시글 블락박스, 모달구현 했습니다. 
현혈견테스트 테스트만 따로 배포했던것처럼 공유하기 기능 변경했습니다. 
깃이그노어에 펨키 추가했습니다(사람마다 펨키이름이다를수있어서 제꺼 추가로적음)
-  #81
> ✨ [Feature] #81 - 비로그인시 모달,블락박스구현 테스트수정

- src/apis/axiosInstance.js
- src/apis/refreshTokenUtil.js
로그인 api 연결 오휴 수정했습니다.  refreshAccessToken에서 axiosInstance를 참조하면서 무한루프가 생긴거같은데... 아무튼 해결했습니다. 
- #81
> 🐛 [Fix] #81 - 로그인 api연결오류수정

- src/components/main/LoginRequiredBox.jsx
- src/components/main/LoginRequiredModal.jsx
- src/pages/mainPage/MainPage.jsx
홈화면 모달 핸드폰 길이에 따라 반응형으로 수정 블락박스 동일 
로그인안했을시 로그인 하시오 프로필 누르면 로그인페이지로 가게 링크 연결함 
-  #81
> 💄 [Design] 홈화면 모달,블락박스 수정

- src/components/main/LoginRequiredModal.jsx
- src/pages/loginPage/WelcomePage.styled.js
- src/pages/mainPage/MainPage.jsx
- src/pages/mainPage/MainPage.styled.js
홈화면 api연결 완료 게시글,필터연결,모달x버튼위치 옮겼습니다. 
-  #81
> ✨ [Feature] #81 - 홈화면 필터,게시글 api연결,모달x버튼위치수정

- src/components/main/PetSlide.jsx
- src/components/main/Post.jsx
- src/components/test/TestQna.styled.js
- src/pages/mainPage/MainPage.jsx
- src/pages/testPage/TestResultNoPage.jsx
반려견 정보등록하는 슬라이드2번 버튼 폰트 수정 
테스트 QA 
답변선택시 배경색 수정, 마지막 헌혈견불가능결과페이지 문구 수정된거 삭제 
둘러보기로 메인페이지 진입시 모달에 로그인하기 버튼을 누르면 기존에는 /login으로 갔는데 그거보다 웰컴페이지로 보내는게 더 맞을듯해서 /로 보내게 수정함 
- #81
> 💄 [Design] #81 슬라이드2번 디자인수정 테스트디자인QA수정 

- src/assets/icons/myBackIcon.svg
- src/pages/myPage/MyPage.jsx
- src/pages/myPage/MyPage.styled.js
마이페이지 첫화면 api연결 완료했고 디자인안맞는게 몇개 있어서 수정했습니다 
폰트 적용 수동으로 되어있는거 테마프로바이더 쓰는거로 변경 
-  #76
> ♻️ [Reafactor] #76 - 마이페이지 api연결, 디자인 안맞는거  수정

- src/components/main/MainSlider.jsx
- src/pages/mainPage/MainPage.jsx
- src/pages/testPage/TestResultNoPage.jsx
- src/pages/testPage/TestResultOkPage.jsx
홈화면에서 로그인한 유저가 테스트를 한번하면 슬라이드에서 테스트하기 슬라이드가 맨뒤로 가게 구현했습니다. 
로그인안한 유저는 테스트를해도 슬라이드 변경안되게 구현함 ㅎㅎ 
- #81
> ✨ [Feature] #81 - 테스트했을때 슬라이드 위치변경

- src/pages/signUpPage/BloodSignUpPage.jsx
- src/pages/signUpPage/GenSignUpPage.jsx
- src/pages/signUpPage/OpSignUpPage.jsx
- src/pages/signUpPage/SignUpPage.styled.js
- 회원가입 페이지 반려견 추가 버튼 클릭하면 디자인 유지되도록 변경
- 회원가입 페이지 혈액형 토글 글씨 줄바꿈 수정
- 회원가입 페이지 혈액형 토글 전체 클릭해도 드롭다운 되도록 변경
- 회원가입 페이지 끄읕!
- #71
> 💄 [Design]/#71 회원가입 페이지 반려견 추가 버튼 클릭되면 디자인 유지되도록 변경, 혈액형 토글 수정

- src/components/community/DropDown.jsx
- src/pages/communityPage/CommunityNew.jsx
- src/pages/communityPage/CommunityNew.styled.js
커뮤니티 메인 구현 완료했습니다. 
api연결도 완료했습니다. 
- #37
> ✨ [Feature] #37 - 커뮤니티메인 구현완료 api연결완료

- src/pages/signUpPage/SignUpPage.jsx
- 이메일 중복 확인 처리 기능 구현 완료
- 이메일 중복 확인 api 연결 완료~
- #71
> [✨Feature]/#71 이메일 중복 확인 처리 기능 구현 완료

- src/pages/chatPage/ChatDetail.styled.js
채팅창에서 헤더는 스크롤돼도 고정되게 수정했습니다. 
- #54
> 💄 [Design] #54 -채팅헤더 상단고정

- src/components/chat/ChatFooter.jsx
- src/pages/chatPage/ChatDetail.styled.js
- src/pages/chatPage/ChatDetailPage.jsx
웹소켓 채팅 드디어 연결은 했습니다. 채팅보내고 f5를 눌러야 보이는 오류가 있어서 추후수정하겠습니다.. 
- #54
> ✨ [Feature] #54 -웹소켓 채팅 작동은됨 오류있음

- src/components/chat/ChatFooter.jsx
- src/pages/chatPage/ChatDetailPage.jsx
웹소켓 채팅완벽구현했습니다 채팅보냈을때 시간도 잘뜨고 다잘뜸 
- #54
> 🐛 [Fix] #54 - 채팅완벽구현완

- src/pages/communityPage/CommunityWrite.jsx
- src/pages/communityPage/CommunityWrite.styled.js
- 커뮤니티 게시물 글쓰기 post API 연결 완료 
- 취소 버튼 경로 수정
POST API 연결 완료! 
GET API 연결까지 하면 상세글 볼 수 있을듯!
#71
> ✨ [Feature] /#71 커뮤니티 게시물 글쓰기 post API 연결 완료 및 취소 버튼 경로 수정

- src/pages/communityPage/CommunityDetail.jsx
- src/pages/communityPage/CommunityDetail.styled.js
- 상세글 삭제 api 연결 완료
- 댓글 빼고는 기능 구현 완료~ 
- 등록 및 삭제 모두 잘됨!
- #71
> ✨ [Feature] /#71 상세글 삭제 api 연결 완료

- src/pages/myPage/AccountManagement.jsx
마이페이지 계정관리 디자인수정 조금했습니다. 채팅약속잡기부터하려고 수정한건  별로없는데 pr올립니다.. 
- #76
> 💄 [Design]/#76

- src/pages/communityPage/CommunityDetail.styled.js
- 댓글 옆에 프로필 이미지 안뜨는 오류 수정
- 댓글 옆에 프로필 이미지 안뜨는 오류 수정
- #113
> 🐛 [Fix]/#113 댓글 옆에 프로필 이미지 안뜨는 오류 수정

- src/components/community/Comment.jsx
- src/pages/communityPage/CommunityDetail.jsx
- 내가 쓴 댓글에는 채팅하기 버튼 없도록 구현
- 내가 쓴 댓글에는 채팅하기 버튼 없도록 구현
- #113
> [✨Feature]/#113  내가 쓴 댓글에는 채팅하기 버튼 없도록 구현

- src/components/mypage/PetCard.jsx
- src/pages/myPage/LegalDocument.styled.jsx
- src/pages/myPage/MyPage.jsx
- src/pages/myPage/MyPage.styled.js
- src/pages/myPage/PetAdd.jsx
- src/pages/myPage/PetAdd.styled.js
- src/pages/myPage/PetEdit.jsx
- src/pages/myPage/PetEdit.styled.js
- src/pages/myPage/PetInfo.jsx
- src/pages/myPage/PetInfo.styled.js
- src/pages/myPage/PrivacyPolicyPage.jsx
- src/pages/myPage/TermsPage.jsx
- src/router.jsx
마이페이지 강아지 프로필수정, 강아지 추가 완료했습니다 
대표강아지 설정도 완료했고 대표강아지가 한마리도 없어도 되는거만 예외처리하면될것같습니다
- #76
> ✨ [Feature] #76 -마이페이지 강아지 추가 수정 완료

- src/components/chat/PromiseCard.jsx
- src/components/main/MainSlider.jsx
- src/components/main/PetSlide.jsx
- src/components/mypage/ReservationCard.jsx
- src/components/mypage/ReservationCard.styled.js
- src/pages/mainPage/MainPage.jsx
- src/pages/mainPage/MainPage.styled.js
- src/pages/myPage/Reservation.jsx
마이페이지 나의 긴급헌혈 약속 api연결완료했습니다. 
채팅에서 약속보기 누르면 이동하는것도구현 완료 
추가로 메인에서 프로필사진안뜨는거랑 슬라이드에서 반려견사진 안뜨는거도 연결완료했습ㄴ다
- #76
> ✨ [Feature] #76 - 헌혈약속 내역 구현완

- src/components/community/Comment.jsx
- src/pages/communityPage/CommunityDetail.jsx
댓글에서 채팅방을 만들때 유저 이메일이 필요해서 백엔드수정하고 프론트에서도 user_email추가하고 채팅방만들기 api연결했습니다.
그런데 채팅방만들기가 백 쪽에서 오류가 있어서 추후 수정해야될듯  
- #54
> ♻️ [Refactor] #54 - 댓글채팅방만들기 props추가 

- src/pages/communityPage/CommunityDetail.jsx
- 댓글 Enter 눌러도 등록되도록 설정
- 댓글 Enter 눌러도 등록되도록 설정
- 댓글 구현 issue 이제 끝....
- #113
> [✨Feature]/#113 댓글 Enter 눌러도 등록되도록 설정

- src/hooks/usePreventZoom.js
- src/pages/chatPage/ChatDetailPage.jsx
- src/pages/communityPage/CommunityDetail.jsx
- src/pages/communityPage/CommunityNew.jsx
- src/pages/loginPage/LoginPage.jsx
16px이하여서 글씨쓸때 확대되는 문제 usePreventZoom훅으로 수정했습니다 
- #136
> 🐛 [Fix] #136 - 글씨쓸때 확대되는거 방지용 훅 개발

- src/pages/myPage/MyPage.jsx
- src/pages/myPage/MyWrite.jsx
- src/pages/myPage/MyWrite.styled.js
- src/router.jsx
- 내가 쓴 글 불러오기 기능 구현 완료
- 내가 쓴 글 불러오기 기능 구현 완료
- #138
> [✨Feature]/#138 내가 쓴 글 불러오기 기능 구현 완료

- src/pages/communityPage/CommunityDetail.jsx
- src/pages/communityPage/CommunityDetail.styled.js
- src/pages/communityPage/CommunitySearch.styled.js
- src/pages/communityPage/CommunityWrite.jsx
- src/pages/myPage/MyWrite.styled.js
- 글쓰고 등록하기 눌렀을때 replace true추가하기
- 게시글 작성할때 이미지 선택사항으로 수정
- 커뮤니티 상세에서 제목에 긴급헌혈/궁금해요 등등 해당항목이 뜨도록 수정
- 모바일에서 가로길이가 짧은 부분 수정
- 게시글 목록들 높이 지정X
- QA 1차 수정
- #143
> 🐛 [Fix]/#143 QA 1차 수정 완료

- src/pages/communityPage/CommunityDetail.jsx
- src/pages/communityPage/CommunityDetail.styled.js
- src/pages/communityPage/CommunitySearch.styled.js
- src/pages/communityPage/CommunityWrite.jsx
- src/pages/myPage/MyWrite.styled.js
오리진에서 커밋 안올라간게 있어서 올려봅니다 ..
- #143
> 🚑 [HotFix] #143 - 커밋 내역 안맞는 부분 수정위한 pr

- src/pages/loginPage/KakaoCallbackPage.jsx
- src/pages/myPage/MyWrite.styled.js
- 카카오 로그인 하면 반려견 추가 페이지로 이동되게 경로 설정
- 카카오 로그인 하면 반려견 추가 페이지로 이동되게 경로 설정
- #143
> [✨ Feature] / #143 카카오 로그인 하면 반려견 추가 페이지로 이동되게 경로 설정

- src/main.jsx
배포는 새로 갱신되었는데 링크접속시 이전버전으로 접속되는문제 config파일에서 업데이트 체크하고 main에 함수추가해서 새 버전이있으면 새로고침되게 수정 
- #136
> ✨ [Feature] #136 - 배포캐시 문제 새로고침하는 코드 추가

- src/components/mypage/PetCard.jsx
- src/components/mypage/PetCard.styled.js
- src/main.jsx
- src/pages/myPage/PetAdd.jsx
- src/pages/myPage/PetEdit.jsx
- src/pages/myPage/PetEdit.styled.js
마이페이지-반려견정보페이지에서 작은화면에서도 프로필 수정과  반려견이름 안짤리게 수정++
사진도 비율맞게 들어가게 수정완
- #136
> 💄 Design#136 - 

- src/pages/communityPage/CommunityDetail.styled.js
- src/pages/communityPage/CommunityNew.jsx
- src/pages/communityPage/CommunitySearch.jsx
- 커뮤니티 사진 규격 수정 
- 최근 검색어 오류 해결
- 커뮤니티 사진 규격 수정 
- 최근 검색어 오류 해결
- #204
> 🐛 [Fix] / #204 : 커뮤니티 사진 규격 수정 및 최근 검색어 오류 해결

- src/pages/communityPage/CommunitySearch.jsx
검색어 삭제 기능 오류 해결
검색어 삭제 기능 오류 해결
전체 삭제 기능은 API 없어서 조만간 연결만 하면 끝날듯합니다아
- #204
> 🐛 [Fix] / #204 : 검색어 삭제 기능 오류 해결

- src/pages/communityPage/CommunitySearch.jsx
- 전체삭제 api 연결 완료
- 전체삭제 api 연결 완료
- #204
> ✨ [Feat] / #204 : 전체삭제 api 연결 완료
